### ISSUE TITLE
No text on android nexus 5/android 5.1

### ISSUE THREAD

**Issue by dbaq** [filestack/filepicker-android#81] opened 2015-05-08 19:47 UTC
Hi,

No text displayed on my nexus 5 device. It is working on fine on the nexus 7.

![2015-05-08 19 41 42](https://cloud.githubusercontent.com/assets/1867703/7544220/0ef10738-f580-11e4-8b84-61855f7036f0.png)

Any idea? Thanks.

**Comment by maciejwitowski** [comment] 2015-05-19 15:51
Hi,

I've never encountered such situation and didn't manage to reproduce it. 

Did you maybe try to clone the repo and debug it locally? You could test what values are provided to the adapter and check either why they are null or why they are not set.

**Comment by dbaq** [comment] 2015-05-19 16:56
Nope, I used ```compile 'io.filepicker:filepicker-android:3.8.13'```. Have you tried on a real nexus 5 device?

**Comment by maciejwitowski** [comment] 2015-05-20 08:28
Yes, I've checked on real nexus 5 with android 5.1.

**Comment by maciejwitowski** [comment] 2015-05-20 15:44
I've managed to reproduce it. The problem is that in the library there is no default theme and it looks like you did not set your application theme as well. I'll work on adding default theme to library and I'll keep you updated.

**Comment by dbaq** [comment] 2015-05-20 21:06
Awesome thanks.

**Comment by janhudzik** [comment] 2016-10-21 08:31
Fixed in bb4efc2df009adf81b538934c558ba4371d20537. Will be avaialbe in 3.10.0 release.

**Closed by janhudzik** 2016-10-21 08:31 UTC
